#!/usr/bin/env python3
"""Generate a Graphite-enabled harfbuzz BUILD.gn from the stock one.

Reads the stock BUILD.gn that ships in the Flutter checkout (GN secondary
source root) and injects the Graphite delta:
  - graphite include dirs in harfbuzz_config
  - the HAVE_GRAPHITE2 define
  - hb-graphite2.cc and the graphite2 engine sources in both source_sets

The result is written to the primary source root
(engine/src/flutter/third_party/harfbuzz/BUILD.gn), which GN prefers over
the secondary copy.

Unlike a static override file, this tracks upstream: when Flutter adds or
removes harfbuzz sources the transform still applies. If the stock file's
structure changes so much that an anchor disappears, this script fails
loudly instead of producing a stale build file.

Usage: graphite_harfbuzz_buildgn.py [path-to-flock-checkout]
Run AFTER `gclient sync` and after cloning graphite into
engine/src/flutter/third_party/graphite.
"""

import sys
from pathlib import Path

GRAPHITE_SOURCES = [
    "../graphite/src/CmapCache.cpp",
    "../graphite/src/Code.cpp",
    "../graphite/src/Collider.cpp",
    "../graphite/src/Decompressor.cpp",
    "../graphite/src/Face.cpp",
    "../graphite/src/FeatureMap.cpp",
    "../graphite/src/FileFace.cpp",
    "../graphite/src/Font.cpp",
    "../graphite/src/GlyphCache.cpp",
    "../graphite/src/GlyphFace.cpp",
    "../graphite/src/Intervals.cpp",
    "../graphite/src/Justifier.cpp",
    "../graphite/src/NameTable.cpp",
    "../graphite/src/Pass.cpp",
    "../graphite/src/Position.cpp",
    "../graphite/src/Segment.cpp",
    "../graphite/src/Silf.cpp",
    "../graphite/src/Slot.cpp",
    "../graphite/src/Sparse.cpp",
    "../graphite/src/TtfUtil.cpp",
    "../graphite/src/UtfCodec.cpp",
    "../graphite/src/direct_machine.cpp",
    "../graphite/src/gr_char_info.cpp",
    "../graphite/src/gr_face.cpp",
    "../graphite/src/gr_features.cpp",
    "../graphite/src/gr_font.cpp",
    "../graphite/src/gr_logging.cpp",
    "../graphite/src/gr_segment.cpp",
    "../graphite/src/gr_slot.cpp",
    "../graphite/src/json.cpp",
]

HB_GRAPHITE_SOURCES = [
    "src/hb-graphite2.cc",
    "src/hb-graphite2.h",
]

INCLUDE_DIRS_STOCK = 'include_dirs = [ "src" ]'
INCLUDE_DIRS_GRAPHITE = """include_dirs = [
    "src",
    "../graphite/src",
    "../graphite/include",
  ]"""


def fail(msg):
    sys.exit(f"graphite_harfbuzz_buildgn: ERROR: {msg}")


def inject_sources(text, target, entries):
    marker = f'source_set("{target}") {{'
    i = text.find(marker)
    if i < 0:
        fail(f"anchor {marker!r} not found in stock BUILD.gn")
    j = text.find("sources = [", i)
    if j < 0:
        fail(f"'sources = [' not found inside source_set({target})")
    insert_at = j + len("sources = [")
    block = "".join(f'\n    "{s}",' for s in entries)
    return text[:insert_at] + block + text[insert_at:]


def main():
    flock = Path(sys.argv[1] if len(sys.argv) > 1 else "flock")
    engine_flutter = flock / "engine" / "src" / "flutter"
    stock_path = (
        engine_flutter
        / "build" / "secondary" / "flutter" / "third_party" / "harfbuzz" / "BUILD.gn"
    )
    dest_path = engine_flutter / "third_party" / "harfbuzz" / "BUILD.gn"
    graphite_dir = engine_flutter / "third_party" / "graphite"

    if not stock_path.is_file():
        fail(f"stock BUILD.gn not found at {stock_path} — did gclient sync run, "
             "or has Flutter moved the secondary source root?")
    if not graphite_dir.is_dir():
        fail(f"graphite checkout not found at {graphite_dir} — clone it first")

    # Validate the graphite source list against the actual checkout so drift
    # in silnrsi/graphite fails here, not deep inside ninja.
    for src in GRAPHITE_SOURCES:
        real = (dest_path.parent / src).resolve()
        if not real.is_file():
            fail(f"graphite source missing from checkout: {src} (expected {real})")

    text = stock_path.read_text()
    if "HAVE_GRAPHITE2" in text:
        fail("stock BUILD.gn already mentions HAVE_GRAPHITE2 — transform is stale?")

    if INCLUDE_DIRS_STOCK not in text:
        fail(f"anchor {INCLUDE_DIRS_STOCK!r} not found in stock BUILD.gn")
    text = text.replace(INCLUDE_DIRS_STOCK, INCLUDE_DIRS_GRAPHITE, 1)

    have_ot = '"HAVE_OT",'
    if have_ot not in text:
        fail(f"anchor {have_ot!r} not found in stock BUILD.gn")
    text = text.replace(have_ot, have_ot + '\n    "HAVE_GRAPHITE2",', 1)

    for target in ("harfbuzz_sources", "harfbuzz_subset"):
        text = inject_sources(text, target, GRAPHITE_SOURCES + HB_GRAPHITE_SOURCES)

    header = (
        "# GENERATED by patch-flutter/scripts/graphite_harfbuzz_buildgn.py —\n"
        "# stock secondary BUILD.gn plus the Graphite delta. Do not edit.\n"
    )
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    dest_path.write_text(header + text)
    print(f"Wrote Graphite-enabled BUILD.gn to {dest_path}")


if __name__ == "__main__":
    main()
