name: Build Flutter Engine with Engine Tool (Matrix)

on:
  push:
    branches: [ "engine-builds" ]
  pull_request:
    branches: [ "engine-builds" ]
env:
  # don't try to install google's internal copy of visual studio
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  FLOCK_REPO: ${{ vars.FLOCK_REPO }}
  FLOCK_BRANCH: ${{ github.ref }}
  FLUTTER_BRANCH: master

jobs:

  build-engine-web:
    # We'll run on whatever OS the matrix entry specifies.
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      max-parallel: 4
      matrix:
        include:

          - name: linux wasm debug unopt (web)
            config_name: wasm_debug_unopt
            os: ubuntu-latest

          - name: linux wasm release (web)
            config_name: wasm_release
            os: ubuntu-latest

          #Error for ci/wasm_release:
          #copying output to /build_outputs/flutter/<engine-revision>/<platform>/<artifact-name>
          #/home/runner/work/_temp/fe7309dc-da91-4034-9c33-5d1b9f653e9b.sh: line 3: out/ci/wasm_release.tar.gz: No such file or directory
          #tar: out/ci/wasm_release: Cannot stat: No such file or directory
          #tar: -: Cannot write: Broken pipe
          #tar: Error is not recoverable: exiting now
          #Error: Process completed with exit code 1.
          #- name: linux ci wasm release (web)
          #  config_name: ci/wasm_release
          #  os: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          path: ''

      - name: assemble flock
        uses: ./.github/actions/assemble-flock
        with:
          flutter_ref: ${{ env.FLUTTER_BRANCH }}
          token: ${{ secrets.REPO_WORKFLOW_PAT }}

      - name: web build
        uses: ./.github/actions/build-and-upload-engine
        with:
          gcp_credentials: ${{ secrets.GOOGLE_STORAGE_BUCKET_SECRET }}
          gcp_bucket: flutter-graphite-builds
          gclient: slim-linux-web
          config_name: ${{ matrix.config_name }}
          engine_version: ${{ github.sha }}


  build-engine-android:
    # We'll run on whatever OS the matrix entry specifies.
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      max-parallel: 4
      matrix:
        include:

          # ubuntu configs

          - name: android debug
            os: ubuntu-latest
            config_name: ci/android_debug

          - name: android debug unopt
            os: ubuntu-latest
            config_name: ci/android_debug_unopt

          - name: android debug arm64
            os: ubuntu-latest
            config_name: ci/android_debug_arm64

          - name: android debug x64
            os: ubuntu-latest
            config_name: ci/android_debug_x64

          - name: android debug x86
            os: ubuntu-latest
            config_name: ci/android_debug_x86

          - name: android embedder debug unopt
            os: ubuntu-latest
            config_name: ci/android_embedder_debug_unopt

          - name: android emulator debug x64
            os: ubuntu-latest
            config_name: ci/android_emulator_debug_x64

          - name: android profile
            os: ubuntu-latest
            config_name: ci/android_profile

          - name: android profile arm64
            os: ubuntu-latest
            config_name: ci/android_profile_arm64

          - name: android profile x64
            os: ubuntu-latest
            config_name: ci/android_profile_x64

          - name: android release
            os: ubuntu-latest
            config_name:  ci/android_release

          - name: android release arm64
            os: ubuntu-latest
            config_name: ci/android_release_arm64

          - name: android release x64
            os: ubuntu-latest
            config_name: ci/android_release_x64

          # macOS configs

          - name: android debug arm64
            os: macos-latest
            config_name: android_debug_arm64

          - name: android debug unopt
            os: macos-latest
            config_name: android_debug_unopt

          - name: android debug unopt arm64
            os: macos-latest
            config_name: android_debug_unopt_arm64

          - name: android profile
            os: macos-latest
            config_name: ci/android_profile

          - name: android profile arm64
            os: macos-latest
            config_name: ci/android_profile_arm64

          - name: android profile x64
            os: macos-latest
            config_name: ci/android_profile_x64

          - name: android release
            os: macos-latest
            config_name:  ci/android_release

          - name: android release arm64
            os: macos-latest
            config_name: ci/android_release_arm64

          - name: android release x64
            os: macos-latest
            config_name: ci/android_release_x64

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: assemble flock
        uses: ./.github/actions/assemble-flock
        with:
          flutter_ref: ${{ env.FLUTTER_BRANCH }}
          token: ${{ secrets.REPO_WORKFLOW_PAT }}

      - name: android build
        uses: ./.github/actions/build-and-upload-engine
        with:
          gcp_credentials: ${{ secrets.GOOGLE_STORAGE_BUCKET_SECRET }}
          gcp_bucket: flutter-graphite-builds
          gclient: slim-linux-android
          config_name: ${{ matrix.config_name }}
          engine_version: ${{ github.sha }}


  build-engine-linux:
    # We'll run on whatever OS the matrix entry specifies.
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash


    strategy:
      max-parallel: 4
      matrix:
        include:


          - name: linux debug arm64
            os: ubuntu-latest
            config_name: ci/linux_debug_arm64

          - name: linux profile arm64
            os: ubuntu-latest
            config_name: ci/linux_profile_arm64
            
          - name: linux release arm64
            os: ubuntu-latest
            config_name: ci/linux_release_arm64

          - name: linux host debug
            config_name: ci/host_debug
            os: ubuntu-latest

          - name: linux host debug clang tidy
            os: ubuntu-latest
            config_name: ci/host_debug_clang_tidy

          - name: linux host debug desktop
            config_name: ci/host_debug_desktop
            os: ubuntu-latest

          - name: linux host debug unopt
            config_name: ci/host_debug_unopt
            os: ubuntu-latest

          - name: linux host release
            os: ubuntu-latest
            config_name: ci/host_release

          - name: linux host release desktop
            os: ubuntu-latest
            config_name: ci/host_release_desktop

          - name: linux host release licenses
            os: ubuntu-latest
            config_name: ci/host_release_licenses

    steps:

      - name: checkout out the repository
        uses: actions/checkout@v4

      - name: assemble flock
        uses: ./.github/actions/assemble-flock
        with:
          flutter_ref: ${{ env.FLUTTER_BRANCH }}
          token: ${{ secrets.REPO_WORKFLOW_PAT }}

      - name: linux build
        uses: ./.github/actions/build-and-upload-engine
        with:
          gcp_credentials: ${{ secrets.GOOGLE_STORAGE_BUCKET_SECRET }}
          gcp_bucket: flutter-graphite-builds
          gclient: slim-linux-desktop
          config_name: ${{ matrix.config_name }}
          engine_version: ${{ github.sha }}
          

      # ------------------------- TESTS BUILDS -------------------------

      # - name: linux host debug test
      #  os: ubuntu-latest
      #  config_name: ci/host_debug_test
      # - name: linux host debug unopt impeller tests
      #  os: ubuntu-latest
      #  config_name: ci/host_debug_unopt_impeller_tests
      # - name: linux host profile desktop
      #  os: ubuntu-latest
      #  config_name: ci/host_profile_desktop
      #- name: linux host profile test
      #  os: ubuntu-latest
      #  config_name: ci/host_profile_test
      #- name: linux host release test
      #  os: ubuntu-latest
      #  config_name: ci/host_release_test
      #- name: android debug test
      #  os: ubuntu-latest
      #  config_name: ci/android_debug_test

  build-engine-mac:
    # We'll run on whatever OS the matrix entry specifies.
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      max-parallel: 4
      matrix:
        include:

         # ------------------------- MAC BUILDS -------------------------

          - name: mac debug arm64
            os: macos-latest
            config_name: ci/mac_debug_arm64

          - name: mac debug framework arm64
            os: macos-latest
            config_name: ci/mac_debug_framework_arm64

          - name: mac debug gen snapshot arm64
            os: macos-latest
            config_name: ci/mac_debug_gen_snapshot_arm64

          - name: mac profile arm64
            os: macos-latest
            config_name: ci/mac_profile_arm64

          - name: mac profile framework arm64
            os: macos-latest
            config_name: ci/mac_profile_framework_arm64

          - name: mac profile gen snapshot arm64
            os: macos-latest
            config_name: ci/mac_profile_gen_snapshot_arm64

          - name: mac release arm64
            os: macos-latest
            config_name: ci/mac_release_arm64

          - name: mac release framework arm64
            os: macos-latest
            config_name: ci/mac_release_framework_arm64

          - name: mac release gen snapshot arm64
            os: macos-latest
            config_name: ci/mac_release_gen_snapshot_arm64

          - name: mac host debug
            os: macos-latest
            config_name: ci/host_debug

          - name: mac host debug clang tidy
            os: macos-latest
            config_name: ci/host_debug_clang_tidy

          - name: mac host debug framework
            os: macos-latest
            config_name:  ci/host_debug_framework

          - name: mac host debug gen snapshot
            os: macos-latest
            config_name: ci/host_debug_gen_snapshot

          - name: mac host debug unopt arm64
            os: macos-latest
            config_name: ci/host_debug_unopt_arm64

          - name: mac host profile
            os: macos-latest
            config_name: ci/host_profile

          - name: mac host profile framework
            os: macos-latest
            config_name: ci/host_profile_framework

          - name: mac host profile gen snapshot
            os: macos-latest
            config_name: ci/host_profile_gen_snapshot

          - name: mac host release
            os: macos-latest
            config_name: ci/host_release

          - name: mac host release arm64 licenses
            os: macos-latest
            config_name: ci/host_release_arm64_licenses
            
          - name: mac host release framework
            os: macos-latest
            config_name: ci/host_release_framework

          - name: mac host release gen snapshot
            os: macos-latest
            config_name: ci/host_release_gen_snapshot

    steps:
   
      - name: Set up Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: assemble flock
        uses: ./.github/actions/assemble-flock
        with:
          flutter_ref: ${{ env.FLUTTER_BRANCH }}
          token: ${{ secrets.REPO_WORKFLOW_PAT }}

      - name: mac build
        uses: ./.github/actions/build-and-upload-engine
        with:
          gcp_credentials: ${{ secrets.GOOGLE_STORAGE_BUCKET_SECRET }}
          gcp_bucket: flutter-graphite-builds
          gclient: slim-mac
          config_name: ${{ matrix.config_name }}
          engine_version: ${{ github.sha }}

  build-macos-release:
    needs: build-engine-mac
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:

      - name: Set up Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      #- name: Authenticate to Google Cloud
      #  uses: google-github-actions/auth@v2
      #  with:
      #    workload_identity_provider: 'projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID'
      #    service_account: 'SERVICE_ACCOUNT_EMAIL'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Setup gcloud
        env:
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_STORAGE_BUCKET_SECRET }}
        run: |
          echo "$GCP_CREDENTIALS"  | base64 -d  > "$HOME"/gcloud.json
          gcloud auth activate-service-account --key-file="$HOME"/gcloud.json

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up depot_tools / gclient
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
          # Append depot_tools to the PATH for subsequent steps
          echo "$HOME/depot_tools" >> $GITHUB_PATH

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: assemble flock
        uses: ./.github/actions/assemble-flock
        with:
          flutter_ref: ${{ env.FLUTTER_BRANCH }}
          token: ${{ secrets.REPO_WORKFLOW_PAT }}
          
      - name: gclient sync macos
        run: |
          # Use custom gclient to trim size
          cd flock
          cp engine/scripts/slim-mac.gclient .gclient
          gclient sync -D

      - name: build macos release
        run: |

          cd flock/engine/src
          
          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/mac_debug_framework_arm64.tar.gz' .
          tar -xzf mac_debug_framework_arm64.tar.gz
          rm mac_debug_framework_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/host_debug_framework.tar.gz' .
          tar -xzf host_debug_framework.tar.gz
          rm  host_debug_framework.tar.gz
          
          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/mac_profile_framework_arm64.tar.gz' .
          tar -xzf mac_profile_framework_arm64.tar.gz
          rm mac_profile_framework_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/host_profile_framework.tar.gz' .
          tar -xzf host_profile_framework.tar.gz
          rm  host_profile_framework.tar.gz
          
          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/mac_release_framework_arm64.tar.gz' .
          tar -xzf mac_release_framework_arm64.tar.gz
          rm mac_release_framework_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/host_release_framework.tar.gz' .
          tar -xzf host_release_framework.tar.gz
          rm  host_release_framework.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/mac_debug_gen_snapshot_arm64.tar.gz' .
          tar -xzf mac_debug_gen_snapshot_arm64.tar.gz
          rm mac_debug_gen_snapshot_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/mac_profile_gen_snapshot_arm64.tar.gz' .
          tar -xzf mac_profile_gen_snapshot_arm64.tar.gz
          rm mac_profile_gen_snapshot_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/mac_release_gen_snapshot_arm64.tar.gz' .
          tar -xzf mac_release_gen_snapshot_arm64.tar.gz
          rm mac_release_gen_snapshot_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/host_debug_gen_snapshot_arm64.tar.gz' .
          tar -xzf host_debug_gen_snapshot_arm64.tar.gz
          rm host_debug_gen_snapshot_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/host_profile_gen_snapshot_arm64.tar.gz' .
          tar -xzf host_profile_gen_snapshot_arm64.tar.gz
          rm host_profile_gen_snapshot_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/host_release_gen_snapshot_arm64.tar.gz' .
          tar -xzf host_release_gen_snapshot_arm64.tar.gz
          rm host_release_gen_snapshot_arm64.tar.gz


          python3 flutter/sky/tools/create_embedder_framework.py \
          --dst out/debug/framework \
          --arm64-out-dir out/ci/mac_debug_framework_arm64 \
          --x64-out-dir out/ci/host_debug_framework \
          --zip

          python3 flutter/sky/tools/create_macos_framework.py \
          --dst out/debug/framework \
          --arm64-out-dir out/ci/mac_debug_framework_arm64 \
          --x64-out-dir out/ci/host_debug_framework \
          --zip

          python3 flutter/sky/tools/create_macos_framework.py \
          --dst out/profile/framework \
          --arm64-out-dir out/ci/mac_profile_framework_arm64 \
          --x64-out-dir out/ci/host_profile_framework \
          --zip

          python3 flutter/sky/tools/create_macos_framework.py \
          --dst out/release/framework \
          --arm64-out-dir out/ci/mac_release_framework_arm64 \
          --x64-out-dir out/ci/host_release_framework \
          --dsym \
          --strip \
          --zip

          python3 flutter/sky/tools/create_macos_gen_snapshots.py \
          --dst out/debug/snapshot \
          --arm64-path out/ci/mac_debug_gen_snapshot_arm64/universal/gen_snapshot_arm64 \
          --x64-path out/ci/host_debug_gen_snapshot/universal/gen_snapshot_x64 \
          --zip

          python3 flutter/sky/tools/create_macos_gen_snapshots.py \
          --dst out/profile/snapshot \
          --arm64-path out/ci/mac_profile_gen_snapshot_arm64/universal/gen_snapshot_arm64 \
          --x64-path out/ci/host_profile_gen_snapshot/universal/gen_snapshot_x64 \
          --zip

          python3 flutter/sky/tools/create_macos_gen_snapshots.py \
          --dst out/release/snapshot \
          --arm64-path out/ci/mac_release_gen_snapshot_arm64/universal/gen_snapshot_arm64 \
          --x64-path out/ci/host_release_gen_snapshot/universal/gen_snapshot_x64 \
          --zip

          gcloud storage cp --recursive out/debug/framework/FlutterEmbedder.framework.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64/
          gcloud storage cp --recursive out/debug/framework/FlutterMacOS.framework.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64/
          gcloud storage cp --recursive out/profile/framework/FlutterMacOS.framework.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64-profile/
          gcloud storage cp --recursive out/release/framework/FlutterMacOS.framework.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64-release/
          gcloud storage cp --recursive out/debug/framework/framework.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64/
          gcloud storage cp --recursive out/profile/framework/framework.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64-profile/
          gcloud storage cp --recursive out/release/framework/framework.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64-release/
          gcloud storage cp --recursive out/debug/snapshot/gen_snapshot.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64/
          gcloud storage cp --recursive out/profile/snapshot/gen_snapshot.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64-profile/
          gcloud storage cp --recursive out/release/snapshot/gen_snapshot.zip gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/darwin-x64-release/

  build-engine-ios:
    # We'll run on whatever OS the matrix entry specifies.
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      max-parallel: 4
      matrix:
        include:
          # ------------------------- iOS BUILDS -------------------------

          - name: ios debug
            config_name: ci/ios_debug
            os: macos-latest

          - name: ios debug sim
            config_name: ci/ios_debug_sim
            os: macos-latest

          - name: ios debug sim arm64
            config_name: ci/ios_debug_sim_arm64
            os: macos-latest

          - name: ios profile
            config_name: ci/ios_profile
            os: macos-latest

          - name: ios release
            config_name: ci/ios_release
            os: macos-latest

          - name: ios debug extension safe
            config_name: ci/ios_debug_extension_safe
            os: macos-latest

          - name: ios debug sim arm64 extension safe
            config_name: ci/ios_debug_sim_arm64_extension_safe
            os: macos-latest

          - name: ios debug sim extension safe
            config_name: ci/ios_debug_sim_extension_safe
            os: macos-latest

          - name: ios debug unopt sim arm64 extension safe
            config_name: ci/ios_debug_unopt_sim_arm64_extension_safe
            os: macos-latest

          - name: ios profile extension safe
            config_name: ci/ios_profile_extension_safe
            os: macos-latest

          - name: ios release extension safe
            config_name: ci/ios_release_extension_safe
            os: macos-latest
    steps:

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: assemble flock
        uses: ./.github/actions/assemble-flock
        with:
          flutter_ref: ${{ env.FLUTTER_BRANCH }}
          token: ${{ secrets.REPO_WORKFLOW_PAT }}

      - name: mac build
        uses: ./.github/actions/build-and-upload-engine
        with:
          gcp_credentials: ${{ secrets.GOOGLE_STORAGE_BUCKET_SECRET }}
          gcp_bucket: flutter-graphite-builds
          gclient: slim-mac
          config_name: ${{ matrix.config_name }}
          engine_version: ${{ github.sha }}

  build-ios-release:
    needs: build-engine-ios
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:

      - name: Set up Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      #- name: Authenticate to Google Cloud
      #  uses: google-github-actions/auth@v2
      #  with:
      #    workload_identity_provider: 'projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID'
      #    service_account: 'SERVICE_ACCOUNT_EMAIL'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Setup gcloud
        env:
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_STORAGE_BUCKET_SECRET }}
        run: |
          echo "$GCP_CREDENTIALS"  | base64 -d  > "$HOME"/gcloud.json
          gcloud auth activate-service-account --key-file="$HOME"/gcloud.json

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up depot_tools / gclient
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
          # Append depot_tools to the PATH for subsequent steps
          echo "$HOME/depot_tools" >> $GITHUB_PATH

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: assemble flock
        uses: ./.github/actions/assemble-flock
        with:
          flutter_ref: ${{ env.FLUTTER_BRANCH }}
          token: ${{ secrets.REPO_WORKFLOW_PAT }}
          
      - name: gclient sync macos
        run: |
          # Use custom gclient to trim size
          cd flock
          cp engine/scripts/slim-mac.gclient .gclient
          gclient sync -D

      - name: build ios release
        run: |

          cd flock/engine/src

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_profile.tar.gz' .
          tar -xzf ios_profile.tar.gz
          rm ios_profile.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_debug.tar.gz' .
          tar -xzf ios_debug.tar.gz
          rm ios_debug.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_release.tar.gz' .
          tar -xzf ios_release.tar.gz
          rm ios_release.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_debug_sim.tar.gz' .
          tar -xzf ios_debug_sim.tar.gz
          rm ios_debug_sim.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_debug_sim_arm64.tar.gz' .
          tar -xzf ios_debug_sim_arm64.tar.gz
          rm ios_debug_sim_arm64.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_release_extension_safe.tar.gz' .
          tar -xzf ios_release_extension_safe.tar.gz
          rm ios_release_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_debug_extension_safe.tar.gz' .
          tar -xzf ios_debug_extension_safe.tar.gz
          rm ios_debug_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_debug_sim_arm64_extension_safe.tar.gz' .
          tar -xzf ios_debug_sim_arm64_extension_safe.tar.gz
          rm  ios_debug_sim_arm64_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_debug_unopt_sim_arm64_extension_safe.tar.gz' .
          tar -xzf ios_debug_unopt_sim_arm64_extension_safe.tar.gz
          rm ios_debug_unopt_sim_arm64_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_debug_sim_extension_safe.tar.gz' .
          tar -xzf ios_debug_sim_extension_safe.tar.gz
          rm ios_debug_sim_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_profile_extension_safe.tar.gz' .
          tar -xzf ios_profile_extension_safe.tar.gz
          rm ios_profile_extension_safe.tar.gz

          gcloud storage cp --recursive 'gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ci/ios_release_extension_safe.tar.gz' .
          tar -xzf ios_release_extension_safe.tar.gz
          rm ios_release_extension_safe.tar.gz


          python3 flutter/sky/tools/create_ios_framework.py \
          --dst out/ios \
          --arm64-out-dir out/ci/ios_debug \
          --simulator-x64-out-dir out/ci/ios_debug_sim \
          --simulator-arm64-out-dir out/ci/ios_debug_sim_arm64 \
          --dsym \
          --strip

          python3 flutter/sky/tools/create_ios_framework.py \
          --dst out/ios_release \
          --arm64-out-dir out/ci/ios_release \
          --simulator-x64-out-dir out/ci/ios_debug_sim \
          --simulator-arm64-out-dir out/ci/ios_debug_sim_arm64 \
          --dsym \
          --strip \

          python3 flutter/sky/tools/create_ios_framework.py \
          --dst out/ios_profile \
          --arm64-out-dir out/ci/ios_profile \
          --simulator-x64-out-dir out/ci/ios_debug_sim \
          --simulator-arm64-out-dir out/ci/ios_debug_sim_arm64 \
          --dsym \
          --strip \

          gcloud storage cp --recursive out/ios/ gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ios/
          gcloud storage cp --recursive out/ios_release/ gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ios_release/
          gcloud storage cp --recursive out/ios_profile/ gs://flutter-graphite-builds/flutter_infra_release/flutter/${{github.sha}}/ios_profile/


  # after we build the engine successfully, it's ok to push our branch
  push-build:
    # needs: build-engine-ios
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: assemble flock
        uses: ./.github/actions/assemble-flock
        with:
          flutter_ref: ${{ env.FLUTTER_BRANCH }}
          token: ${{ secrets.REPO_WORKFLOW_PAT }}

      # Compute an engine version hash so the flutter tool will be able to find a precompiled engine
      - name: save engine hash
        shell: bash
        run: |
          cd flock
          echo "${{ github.sha }}" > ./bin/internal/engine.version
          git add -f ./bin/internal/engine.version
          git config --global user.email "no-reply@getflocked.dev"
          git config --global user.name "Flock"
          git commit -m "save engine version" --allow-empty

      - name: update our remote flock branch to use this engine hash
        uses: ./.github/actions/push-flock-repo
        with:
          destination_repo: ${{ env.FLOCK_REPO }}
          destination_branch: ${{ env.FLOCK_BRANCH }}
